import { AiOutlineDashboard } from "react-icons/ai";

export const allNav = [
    {
        id: 1,
        title: "Kích hoạt đăng ký lịch dạy",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/activate-teaching-schedule-registration",
    },
    {
        id: 2,
        title: "Quản lý lớp học",
        icon: <AiOutlineDashboard />,
        role: ["admin", "employee"],
        path: "/classroom",
    },
    {
        id: 3,
        title: "Kích hoat đăng ký tín chỉ",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/enable-credit-registration",
    },
    {
        id: 4,
        title: "Quản lý khoa",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/faculty",
    },
    {
        id: 5,
        title: "Quản lý giảng viên",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/lecturer_management",
    },
    {
        id: 6,
        title: "Quản lý ngành học",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/major",
    },
    {
        id: 7,
        title: "Quản lý thông tin cá nhân",
        icon: <AiOutlineDashboard />,
        role: ["admin", "employee", "student", "lecturer"],
        path: "/profile",
    },
    {
        id: 8,
        title: "Quản lý chuyên ngành học",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/specialization",
    },
    {
        id: 9,
        title: "Quản lý sinh viên",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/student_management",
    },
    {
        id: 10,
        title: "Quản lý học phần",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/subject",
    },
    {
        id: 10,
        title: "Quản lý chương trình đào tạo",
        icon: <AiOutlineDashboard />,
        role: ["admin"],
        path: "/training-program",
    },
];
